spring.application.name=FoodBite


#MongoDb configuration


#spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/food?authSource=admin
#spring.data.mongodb.uri=mongodb://localhost:27017/test
#spring.data.mongodb.uri=mongodb://mongodb:27017/test
#spring.data.mongodb.uri=mongodb://admin:admin123@mongo:27017/foodbite_db?authSource=admin
# local run ?? ???
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/foodbite_db}





# aws s3 configuration

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_BUCKET}

jwt.secret.key=${JWT_SECRET_KEY}
